name: Test Expect Self Parameter Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run expect-self-parameter action
        uses: ./  # This points to the local action in the repository
        with:
          params: >
            {
              "workflow": {
                "on": "[push, pull_request]"
              },
              "jobs.test": {
                "runs-on": "ubuntu-latest"
              },
              "steps.foo": {
                "continue-on-error": "true"
              },
              "steps.bar": {
                "timeout-minutes": "10"
              }
            }

      - id: foo
        run: echo hello
        continue-on-error: false

      - id: bar
        run: sleep 5
        timeout-minutes: 10
